name: wajah_id
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^4.1.2+1
  change_app_package_name: ^1.0.0
  dio: 1.0.0
  google_fonts: ^1.1.2
  url_launcher: ^6.0.2
  flutter_svg: ^0.22.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  flutter_icons: ^1.1.0
  flutter_tabler_icons: ^1.0.2
  flare_flutter: ^3.0.2
  cloud_firestore: ^0.16.0
  provider: ^4.3.3
  cool_alert: ^1.0.3
  google_nav_bar: ^5.0.2
  font_awesome_flutter: ^8.12.0
  carousel_slider: ^3.0.0
  typicons_flutter: ^0.4.2
  quick_actions: ^0.5.0
  introduction_screen: ^2.0.0
  mvc_pattern: ^8.2.2
  titled_navigation_bar: ^4.1.0
  animated_size_and_fade: ^3.0.0
  progress_state_button: ^1.0.3
  cached_network_image: ^2.5.1
  shimmer: ^2.0.0
  internet_connection_checker: ^0.0.1+3
  nanoid: ^1.0.0
  page_indicator: ^0.4.1
  rect_getter: ^1.1.0
  expandable: ^5.0.1
  date_picker_timeline: ^1.2.1
  intl: ^0.16.1
  dropdown_search: ^3.0.1
  http: ^0.12.2
  get: ^4.6.1
  flutter_rating_bar: ^4.0.1






#  selectable_circle_list: ^0.1.5+1
#  firebase_image: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_launcher.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/skin_products/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300

    - family: PantonBold
      fonts:
        - asset: assets/fonts/panton/Panton-BlackCaps.otf

    - family: PantonBoldItalic
      fonts:
        - asset: assets/fonts/panton/Panton-BlackitalicCaps.otf

    - family: Panton
      fonts:
        - asset: assets/fonts/panton/Panton-LightCaps.otf

    - family: PantonItalic
      fonts:
        - asset: assets/fonts/panton/Panton-LightitalicCaps.otf
  # To add assets to your application, add an assets section, like this:
  #  assets:
  #    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
