final doctorMapList = [
  {
    "name": "dr. Alfina Damayanti, Sp.KK",
    "type": "Skin Specialist",
    "price": "100000",
    "rating": 4.5,
    "experience": 5,
    "goodReviews": 79.2,
    "totalScore": 93.2,
    "satisfaction": 85.2,
    "isfavourite": true,
    "image":"assets/doctor_example.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "dr. Putri Anggraini Kristanti, Sp.KK",
    "type": "Skin Specialist",
    "price":" 100000",
    "rating": 3.5,
    "experience": 4,
    "goodReviews": 93.2,
    "totalScore": 72.2,
    "satisfaction": 89.2,
    "isfavourite": false,
    "image":"assets/doctor_example.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "dr. Farah Khoirunnisa, Sp.KK",
    "type": "Skin Specialist",
    "price": "100000",
    "rating": 2.5,
    "experience": 3,
    "goodReviews": 88.2,
    "totalScore": 93.94,
    "satisfaction": 78.2,
    "isfavourite": false,
    "image": "assets/doctor_example.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "Dr. Bruce Banner",
    "type": "Skin Specialist",
    "price": "100000",
    "rating": 1.5,
    "goodReviews": 12.2,
    "totalScore": 75.2,
    "satisfaction": 84.2,
    "isfavourite": true,
    "image": "assets/doctor_example.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  }
];